version: '3.8'

services:
  # === БАЗА ДАННЫХ ===
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      # Подтягиваем переменные из .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # === BACKEND ===
  backend:
    build: .
    container_name: moviehub_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/src/app
      - ./static:/src/static
      - ./main.py:/src/main.py
      - ./alembic:/src/alembic
    environment:
      # Подтягиваем полную строку подключения из .env
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    build: ./kino-frontend   # Строим из папки фронта
    container_name: moviehub_frontend
    ports:
      - "5173:5173"
    volumes:
      # Пробрасываем код фронта для Hot Reload
      - ./kino-frontend:/app
      # Исключаем node_modules, чтобы не конфликтовали версии
      - /app/node_modules
    environment:
      # Указываем, что нужно использовать опрос (polling) для отслеживания изменений,
      # что необходимо для работы Live Reload в Docker на Windows/Mac
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
    # Добавляем команду для запуска dev-сервера (если не указана в Dockerfile)
    command: npm run dev

volumes:
  postgres_data: