version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # === BACKEND ===
  backend:
    build: .
    container_name: moviehub_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/src/app
      - ./static:/src/static
      - ./main.py:/src/main.py
      - ./alembic:/src/alembic
    environment:
      DATABASE_URL: ${DATABASE_URL}

  telegram_bot:
    build: .
    container_name: moviehub_telegram_bot
    depends_on:
      - backend
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_ADMIN_USERNAMES: ${TELEGRAM_ADMIN_USERNAMES}
      ADMIN_API_BASE_URL: http://backend:8000/api
    command: ["python", "-m", "telegram_bot.bot"]

  frontend:
    build: ./kino-frontend
    container_name: moviehub_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./kino-frontend:/app
      - /app/node_modules
    environment:

      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
    command: npm run dev

volumes:
  postgres_data: